Resources:
  UserAnswer:
    Type: AWS::DynamoDB::Table
    Properties:
      "AttributeDefinitions":
        - "AttributeName": "QuestionId"
          "AttributeType": "N"
      "KeySchema":
        - "AttributeName": "QuestionId"
          "KeyType": "HASH"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      BillingMode: PAY_PER_REQUEST
      TableName: "QuestionCountsLambda"