Resources:
  CategoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      "AttributeDefinitions":
        - "AttributeName": "userName"
          "AttributeType": "S"
        - "AttributeName": "userId"
          "AttributeType": "S"
      "KeySchema":
        - "AttributeName": "userId"
          "KeyType": "HASH"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      BillingMode: PAY_PER_REQUEST
      TableName: "user"